name: Build Linphone

on:
  push:
    branches: ['main']

concurrency:
  group: build-linphone
  cancel-in-progress: true

jobs:
  checks:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: 'extra-experimental-features = nix-command flakes ca-derivations'

      - uses: cachix/cachix-action@v14
        with:
          name: naxdy-foss
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Package
        run: |
          nix build .#linphone-desktop --print-build-logs --show-trace
